CREATE TABLE BOOKINGS (
    BOOKING_ID INT PRIMARY KEY,
    BOOKING_DATE DATE,
    EVENT_ID INT,
    ARTIST_ID VARCHAR2(10)
);


CREATE OR REPLACE TRIGGER trg_prevent_invalid_booking
BEFORE INSERT ON BOOKINGS
FOR EACH ROW
DECLARE
    v_day VARCHAR2(3);
BEGIN
    v_day := TO_CHAR(:NEW.BOOKING_DATE, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH');
    IF v_day IN ('SAT', 'SUN') THEN
        RAISE_APPLICATION_ERROR(-20001, 'Bookings cannot be made on weekends.');
    END IF;
END;
/



INSERT INTO BOOKINGS (BOOKING_ID, BOOKING_DATE, EVENT_ID, ARTIST_ID) 
VALUES (1, TO_DATE('2025-06-21', 'YYYY-MM-DD'), 100, 'A001');


INSERT INTO BOOKINGS (BOOKING_ID, BOOKING_DATE, EVENT_ID, ARTIST_ID) 
VALUES (2, TO_DATE('2025-06-23', 'YYYY-MM-DD'), 100, 'A001');